name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: |
          make test
      - name: Update Documentation
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sudo make install-asciidoctor
          make archive VERSION="${{ github.ref }}"
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "quote-and-join.zip"
          bodyFile: "README.md"
