name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "check out the repo"
        uses: actions/checkout@v3
      - name: "Test"
        run: |
          make test
      - name: "make release"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sudo make install-asciidoctor
          make archive VERSION="${{ github.ref }}"
      - name: "upload release"
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "quote-and-join.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}