name: Quote And Join
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Functional-Tests-QAJ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: make test
