name: Quote And Join
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Functional-Tests-QAJ:
    runs-on: ubuntu-latest
    steps:
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: pwd
        run: pwd ; ls
      - name: tests
        run: make test
